# Generated by Django 5.2.7 on 2025-11-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
