# Generated by Django 5.2.7 on 2025-11-15 14:43

import account.models
import django.core.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('pfp', models.ImageField(null=True, upload_to=account.models.upload_to)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=6)),
                ('address', models.TextField(null=True)),
                ('document_type', models.CharField(choices=[('NIN', 'National ID Card / NIN Slip'), ('PASSPORT', 'International Passport'), ('PHOTO', 'Passport Photograph'), ('DL', "Driver's License"), ('PVC', "Permanent Voter's Card"), ('UTILITY', 'Utility Bill')], default='NIN', max_length=30, null=True)),
                ('document_image', models.ImageField(null=True, upload_to=account.models.business_files)),
                ('bvn_number', models.CharField(help_text='Bank Verification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit BVN.', regex='^\\d{11}$')])),
                ('tin_number', models.CharField(help_text='TAX Identification Number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TIN (8-4 format or 12 digits).', regex='^(?:\\d{8}-\\d{4}|\\d{12})$')])),
                ('is_verifed', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
