# Generated by Django 5.2.7 on 2025-11-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
